# Generated by Django 5.1.1 on 2024-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
